# -*- coding: utf-8 -*-
"""ENG220Assignment5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gukx7VZZESpPWs69SBYgW1VzuU3HYghl
"""

# prompt: Web application using streamlit that visualizes a pre-loaded dataset


import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Load your dataset
data = pd.read_csv("your_dataset.csv")  # Replace "your_dataset.csv" with your file path

# Title of your app
st.title("Dataset Visualization App")

# Display the dataset
st.subheader("Dataset:")
st.dataframe(data)

# Visualizations
st.subheader("Visualizations:")

# Example: Histogram of a column
column_to_plot = st.selectbox("Select a column to plot:", data.columns)
if column_to_plot:
    fig, ax = plt.subplots()
    ax.hist(data[column_to_plot])
    ax.set_xlabel(column_to_plot)
    ax.set_ylabel("Frequency")
    st.pyplot(fig)

# Example: Scatter plot of two columns
x_axis = st.selectbox("Select X-axis:", data.columns)
y_axis = st.selectbox("Select Y-axis:", data.columns)
if x_axis and y_axis:
    fig, ax = plt.subplots()
    ax.scatter(data[x_axis], data[y_axis])
    ax.set_xlabel(x_axis)
    ax.set_ylabel(y_axis)
    st.pyplot(fig)

# You can add more visualizations as needed (bar charts, line plots, etc.)