# -*- coding: utf-8 -*-
"""ENG220ClassAssignment5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gukx7VZZESpPWs69SBYgW1VzuU3HYghl
"""

# prompt: Simple Web application using streamlit that visualizes a pre-loaded dataset

# Install streamlit if not already installed

# Import necessary libraries
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# Load your dataset (replace with your actual dataset)
data = pd.read_csv('your_dataset.csv')  # Replace 'your_dataset.csv' with the actual file path


# Set the title of the app
st.title("Dataset Visualization")


# Display the dataset
st.subheader("Dataset")
st.dataframe(data)


# Create visualizations
st.subheader("Visualizations")

# Histogram of a specific column
column_to_visualize = st.selectbox("Select a column to visualize", data.columns)

if column_to_visualize:
  fig, ax = plt.subplots()
  sns.histplot(data[column_to_visualize], ax=ax)
  st.pyplot(fig)


# Scatter plot of two columns
x_column = st.selectbox("Select X-axis column", data.columns)
y_column = st.selectbox("Select Y-axis column", data.columns)

if x_column and y_column:
  fig, ax = plt.subplots()
  sns.scatterplot(data=data, x=x_column, y=y_column, ax=ax)
  st.pyplot(fig)


# You can add more visualizations based on your needs, such as bar charts, box plots, etc.



# Run the Streamlit app
if __name__ == '__main__':
  st.write("Streamlit app is running...")