# -*- coding: utf-8 -*-
"""ENG220Assignment5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gukx7VZZESpPWs69SBYgW1VzuU3HYghl
"""

import streamlit as st
import pandas as pd

# Title of the app
st.title('Interactive Iris Data Visualization App')

# Pre-loaded dataset (Iris dataset)
data = {
    'Sepal Length (cm)': [5.1, 4.9, 4.7, 4.6, 5.0],
    'Sepal Width (cm)': [3.5, 3.0, 3.2, 3.1, 3.6],
    'Petal Length (cm)': [1.4, 1.4, 1.3, 1.5, 1.4],
    'Petal Width (cm)': [0.2, 0.2, 0.2, 0.2, 0.2],
    'Species': ['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa']
}

df = pd.DataFrame(data)

# Display the dataset
st.write("Iris Data (Sample):")
st.write(df)

# Get list of numeric columns only
numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns.tolist()

# Dropdowns for X and Y axes selection, showing only numeric columns
x_axis = st.selectbox('Select column for X-axis', numeric_columns)
y_axis = st.selectbox('Select column for Y-axis', numeric_columns)

# Choose chart type: Bar Chart or Line Chart
chart_type = st.selectbox('Select chart type', ['Bar Chart', 'Line Chart'])

# Display chart based on user selections
if chart_type == 'Bar Chart':
    st.bar_chart(df[[x_axis, y_axis]].set_index(x_axis))
elif chart_type == 'Line Chart':
    st.line_chart(df[[x_axis, y_axis]].set_index(x_axis))
