# -*- coding: utf-8 -*-
"""ENG220ClassAssignment5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gukx7VZZESpPWs69SBYgW1VzuU3HYghl
"""

import streamlit as st
import pandas as pd
from sklearn import datasets

# Load dataset
iris = datasets.load_iris()
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Sidebar
st.sidebar.title('Iris Dataset Visualizer')

# Show dataset
if st.sidebar.checkbox('Show Dataset'):
    st.subheader('Iris Dataset')
    st.write(iris_df)

# Scatter plot
st.sidebar.subheader('Scatter plot options')
x_axis = st.sidebar.selectbox('Select x-axis', iris_df.columns)
y_axis = st.sidebar.selectbox('Select y-axis', iris_df.columns)

st.subheader('Scatter plot')
st.write(f"Visualizing iris dataset using {x_axis} and {y_axis}")
st.scatter_chart(iris_df[[x_axis, y_axis]])

# Footer
st.sidebar.text('Built with Streamlit')